apiVersion: builtin
kind: LabelTransformer
metadata:
  name: notImportantHere
labels:
  networking/allow-internet-access: "true"
fieldSpecs:
- kind: Deployment
  path: spec/template/metadata/labels
  create: true