apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/network/allow-ingress-nginx.yml
- resources/network/hibernation-allow-ingress-nginx.yaml
- resources/network/cert-manager-allow-all.yaml
- resources/network/agent-controller-ingress.yml
- resources/network/controller-cjoc-ingress.yaml
- resources/network/deny-all-ingress.yml
- resources/cbci-mc-secret-provider.yml
- resources/controller-secrets-pod.yaml
- resources/controller-limit-range.yaml
- resources/controller-resource-quota.yaml
- chart.yaml
transformers:
  - transformers/pod-labels.yaml
patches:
  - path: patches/controller-rolebinding-patch.yaml
    target:
      kind: RoleBinding
      name: cjoc-master-role-binding
