apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: patches/controller-rolebinding-patch.yaml
    target:
      kind: RoleBinding
      name: cjoc-master-role-binding
resources:
- resources/network/allow-ingress-nginx.yml
- resources/network/agent-controller-ingress.yml
- resources/network/controller-cjoc-ingress.yaml
- resources/network/deny-all-ingress.yml
- resources/controllers-namespace.yml
- resources/cbci-mc-secret-provider.yml
- resources/controller-limit-range.yaml
- resources/controllers-resource-quota.yaml
- resources/manage-subnamespaces-role.yaml
- resources/manage-subnamespaces-rolebinding.yaml
- chart.yaml