apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: cbci-cjoc-secret-provider
  namespace: cbci
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/core-workshop/secrets/cbci-oc-admin-password/versions/latest"
        fileName: "cbciCjocAdminPassword"