apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: cbci-ops-secret-provider
  namespace: cbci
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-attendee-password/versions/latest"
        fileName: "cbciWorkshopAttendeePassword"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-ops-github-app-pem/versions/latest"
        fileName: "opsGitHubAppPrivateKey"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-github-app-pem/versions/latest"
        fileName: "workshopGitHubAppPrivateKey"
      - resourceName: "projects/core-workshop/secrets/cbci-pipeline-workshop-github-app-pem/versions/latest"
        fileName: "cbciPipelineWorkshopGitHubAppPrivateKey"
      - resourceName: "projects/core-workshop/secrets/staging-cbci-workshop-github-app-pem/versions/latest"
        fileName: "staging-workshopGitHubAppPrivateKey"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-slack-token/versions/latest"
        fileName: "workshopSlackToken"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-oc-admin-api-token/versions/latest"
        fileName: "apiToken"
      - resourceName: "projects/core-workshop/secrets/cbff-workshop-github-app-pem/versions/latest"
        fileName: "featureFlagWorkshopGitHubAppPrivateKey"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-github-app-webhook-secret/versions/latest"
        fileName: "gitHubWebhookSecret"
      - resourceName: "projects/core-workshop/secrets/cbci-casc-workshop-github-app-pem/versions/latest"
        fileName: "cbciCascWorkshopGitHubAppPrivateKey"
      - resourceName: "projects/core-workshop/secrets/cbci-casc-workshop-github-app-id/versions/latest"
        fileName: "cbciCascWorkshopGitHubAppId"
      - resourceName: "projects/core-workshop/secrets/cbci-casc-workshop-controller-provision-secret/versions/latest"
        fileName: "cbciCascWorkshopControllerProvisionSecret"
      - resourceName: "projects/core-workshop/secrets/staging-cbci-casc-workshop-github-app-pem/versions/latest"
        fileName: "staging-cbciCascWorkshopGitHubAppPrivateKey"
      - resourceName: "projects/core-workshop/secrets/cbci-kubernetes-workshop-github-app-pem/versions/latest"
        fileName: "cbciKubernetesWorkshopGitHubAppPrivateKey"
                