apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cbci-cjoc-secret-provider
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/core-workshop/secrets/cbci-oc-admin-password/versions/latest"
        fileName: "cbciCjocAdminPassword"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-oc-admin-api-token/versions/latest"
        fileName: "cbciWorkshopCjocAdminToken"
      - resourceName: "projects/core-workshop/secrets/cbci-casc-workshop-user-api-token/versions/latest"
        fileName: "userApiToken"
      - resourceName: "projects/core-workshop/secrets/cbci-casc-workshop-github-app-pem/versions/latest"
        fileName: "cbciCascWorkshopGitHubAppPrivateKey"
