apiVersion: apps/v1
kind: Deployment
metadata:
  name: smee-oc-client
  namespace: cbci
  labels:
    app: smee-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smee-client
  template:
    metadata:
      namespace: cbci
      labels:
        app: smee-client
    spec:
      serviceAccountName: jenkins
      containers:
        - name: "oc-smee-client"
          image: "deltaprojects/smee-client:latest"
          args: ["-t", "http://cjoc.cbci.svc.cluster.local/cjoc/webhooks/KrlkwAD/", "--url", "http://smee.cbci.svc.cluster.local/hvAj14tSAi7yb7E"]
