apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: cbci-mc-secret-provider
  namespace: sda
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/core-workshop/secrets/staging-cbci-workshop-github-app-pem/versions/latest"
        fileName: "gitHubAppPrivateKey"
      - resourceName: "projects/core-workshop/secrets/staging-cbci-workshop-github-app-id/versions/latest"
        fileName: "gitHubAppId"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-slack-token/versions/latest"
        fileName: "slackToken"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-github-app-webhook-secret/versions/latest"
        fileName: "gitHubWebhookSecret"
      - resourceName: "projects/core-workshop/secrets/cbff-workshop-github-app-pem/versions/latest"
        fileName: "featureFlagWorkshopGitHubAppPrivateKey"
