apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: cbci-oc-init-groovy
  files:
    - config/init_groovy/09-license-activate.groovy
- name: cbci-oc-quickstart-groovy
  files:
    - config/groovy-quickstart/04-create-k8s-secret-with-jenkins-token.groovy
    - config/groovy-quickstart/07-create-k8s-shared-cloud.groovy
- name: oc-casc-bundle
  files:
    - casc/oc/bundle.yaml
    - casc/oc/jenkins.yaml
    - casc/oc/plugins.yaml
    - casc/oc/items.yaml
resources:
- resources/network/cert-manager-allow-all.yaml
- resources/network/allow-ingress-nginx.yml
- resources/network/cjoc-controller-ingress.yaml
- resources/network/cjoc-smee-client-ingress.yaml
- resources/network/controller-cjoc-ingress.yaml
- resources/network/smee-smee-client-ingress.yaml
- resources/network/deny-all-ingress.yml
- resources/cluster-issuers.yml
- resources/regional-pd-ssd.yaml
- resources/cbci-cjoc-secret-provider.yml
- resources/cbci-ops-secret-provider.yml
- chart.yaml
transformers:
  - transformers/pod-labels.yaml
patches:
  - path: patches/workload-identity-sa-patch.yaml
    target:
      kind: ServiceAccount
      name: jenkins
  - path: patches/workload-identity-sa-patch.yaml
    target:
      kind: ServiceAccount
      name: cjoc
