apiVersion: v1
kind: LimitRange
metadata:
  name: controller-limit-range
spec:
  limits:
  - default:
      cpu: "1"
      memory: 1Gi
    defaultRequest:
      cpu: "500m"
      memory: 512Mi
    max:
      cpu: "2"
      memory: 4Gi
    type: Container