apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cjoc-role-binding
  namespace: controllers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manage-subnamespaces
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: cbci

