apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: not-important
spec:
  serviceName: cjoc
  template:
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000